server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
#    password: Penrose54321
#    url: jdbc:postgresql://ratemyclass-db.csw3zfbuwic8.us-east-1.rds.amazonaws.com:5432/postgres
#    username: postgres
#    driver-class-name: org.postgresql.Driver
#    password: Penrose123
    url: jdbc:h2:mem:testdb
    username: sa
    driver-class-name: org.h2.Driver
    password: password


  h2:
    console.enabled: true


  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    show-sql: true


#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        format_sql: true
#    show-sql: true

#  mail:
#    host: localhost
#    port: 1025
#    username: hello
#    password: hello
#
#    properties:
#      mail:
#        smtp:
#          ssl:
#            trust: "*"
#          auth: true
#          starttls:
#            enable: true
#          connectiontimeout: 5000
#          timeout: 3000
#          writetimeout: 5000

